id: P002968
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16917
  title: སངས་རྒྱས་ཀྱི་གཙུག་ཏོར་དཔའ་བར་འགྲོ་བ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
  author: ''
  volumes:
    03b700b8e5484b43b3ae7a9109f5029f:
      image_group_id: I1KG16942
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
